version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore MyApp/MyApp.sln
build:
  project: MyApp/MyApp.sln
  verbosity: minimal

test_script:
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.x86.exe" -targetargs:"MyTests\bin\Debug\MyTests.dll -noshadow" -output:".\coverage.xml" -filter:"+[MyApp*]* -[MyTests*]*"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "MyApp/coverage.xml" -t 92689bfe-74fc-417e-b4a0-bf231a0f901b